/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package soc1;

import java.io.*;
import java.net.*;
import java.sql.*;
import java.util.ArrayList;
/**
 *
 * @author user
 */
public class P3ReceiveTask extends javax.swing.JFrame {

    /**
     * Creates new form P3ReceiveTask
     */
    double[] etij,wtij,btij;
    double budget;
    Connection con;
    Statement st;
    
    public P3ReceiveTask() {
        initComponents();
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/socDB","root","");
            st=con.createStatement();
            
        }
        catch(Exception e){
            System.out.println("Exception1 : "+e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        V = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        e1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(920, 540));
        getContentPane().setLayout(null);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 110, 900, 10);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 160, 900, 10);

        V.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        V.setForeground(new java.awt.Color(0, 102, 255));
        V.setText("Receive Task");
        V.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 204, 255), new java.awt.Color(102, 204, 255), null, null));
        V.setContentAreaFilled(false);
        V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VActionPerformed(evt);
            }
        });
        getContentPane().add(V);
        V.setBounds(10, 120, 130, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 180, 330, 300);

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 120, 560, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User Constraints", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18), new java.awt.Color(0, 102, 255))); // NOI18N
        jPanel1.setOpaque(false);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(370, 160, 510, 200);

        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(370, 370, 300, 120);

        e1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        e1.setForeground(new java.awt.Color(0, 102, 255));
        e1.setText("Send Query");
        e1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 204, 255), new java.awt.Color(102, 204, 255), null, null));
        e1.setContentAreaFilled(false);
        e1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e1ActionPerformed(evt);
            }
        });
        getContentPane().add(e1);
        e1.setBounds(760, 120, 130, 27);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tit.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VActionPerformed
        // TODO add your handling code here:
        try {
            Socket s=new Socket("localhost",1000);            
            BufferedReader br=new BufferedReader(new InputStreamReader(s.getInputStream()));
            
            String id=br.readLine();
            String fileName=br.readLine();            
            String fName=id+"_"+fileName;
            String idfName=fName;
            String read="";
            int noOfRes=Integer.parseInt(br.readLine());
            
            //System.out.println("hello");
            
            etij=new double[noOfRes];
            wtij=new double[noOfRes];
            btij=new double[noOfRes];
            
            for(int i=0;i<etij.length;i++){
                etij[i]=Double.parseDouble(br.readLine());
                System.out.println("e "+etij[i]); 
            }
            
            //System.out.println("hello"); 
            
            for(int i=0;i<wtij.length;i++){
                wtij[i]=Double.parseDouble(br.readLine());
                System.out.println("w "+wtij[i]);
            }
            
            //System.out.println("hello");
            
            for(int i=0;i<btij.length;i++){
                btij[i]=Double.parseDouble(br.readLine());
                System.out.println("b "+btij[i]);
            }
            
            //System.out.println("hello");
            
            budget=Double.parseDouble(br.readLine());
            
            //System.out.println("hello");
            
            BufferedWriter bw=new BufferedWriter(new FileWriter("./TaskReceived/"+fName));
            while((read=br.readLine())!=null)
            {
                //System.out.println("hellor");
                jTextArea1.append(read+"\n");
                bw.write(read);
                bw.newLine();
            }
            bw.close();
            s.close();

            //System.out.println("helloxx");
            
            jLabel2.setText("Task Received successfully with user constraints !");
            
            jTextArea2.append("Resources\te(tij)\tw(tij)\tBudget\n-----------------------------------------------------\n");
            jTextArea2.append("Memory\t"+etij[0]+"\t"+wtij[0]+"\t"+btij[0]+"\n");
            jTextArea2.append("Cpu Usage\t"+etij[1]+"\t"+wtij[1]+"\t"+btij[1]+"\n");
            jTextArea2.append("Vir. Mem\t"+etij[2]+"\t"+wtij[2]+"\t"+btij[2]);
            
            jTextArea3.append("Task Id : "+id+"\n\n");
            jTextArea3.append("Budget  : "+budget);

            st.executeUpdate("insert into task values('"+idfName+"','memory',"+etij[0]+","+wtij[0]+","+btij[0]+","+budget+")");
            st.executeUpdate("insert into task values('"+idfName+"','cpu',"+etij[1]+","+wtij[1]+","+btij[1]+","+budget+")");
            st.executeUpdate("insert into task values('"+idfName+"','vm',"+etij[2]+","+wtij[2]+","+btij[2]+","+budget+")");
            
        } catch (Exception e) {
            System.out.println("Exception1 " + e);
        }
    }//GEN-LAST:event_VActionPerformed

    private void e1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e1ActionPerformed
        // TODO add your handling code here:
        ResourceQuery c = new ResourceQuery();
        c.setVisible(true);
    }//GEN-LAST:event_e1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(P3ReceiveTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(P3ReceiveTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(P3ReceiveTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(P3ReceiveTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new P3ReceiveTask().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton V;
    private javax.swing.JButton e1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
}
