/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package soc1;

import java.awt.Color;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author user
 */
public class ResourceQuery extends javax.swing.JFrame {

    /**
     * Creates new form ResourceQuery
     */
    Connection con;
    Statement st;
    ResultSet rs;
    public static String taskId="";
    public static double e[]=new double[3];
    public static double w[]=new double[3];
    public static double b=0.0;
    
    public ResourceQuery() {
        initComponents();
        try
        {
            UIManager.put("OptionPane.background", Color.WHITE);
            UIManager.put("Panel.background", Color.WHITE);
            UIManager.put("Button.background",Color.WHITE);
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/socDB","root","");
            st=con.createStatement();
        }
        catch(Exception e){
            System.out.println("Exception : "+e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        query = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(920, 540));
        getContentPane().setLayout(null);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 110, 900, 10);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 160, 900, 10);

        query.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        query.setForeground(new java.awt.Color(0, 102, 255));
        query.setText("Send Query");
        query.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 204, 255), new java.awt.Color(102, 204, 255), null, null));
        query.setContentAreaFilled(false);
        query.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queryActionPerformed(evt);
            }
        });
        getContentPane().add(query);
        query.setBounds(10, 120, 170, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Traditional Arabic", 0, 22)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 102, 255));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 190, 860, 120);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tit.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void queryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queryActionPerformed
        // TODO add your handling code here:
        try {
            
            rs=st.executeQuery("select count(*) from task");
            int count=0;
            while(rs.next()){
                count=rs.getInt(1);
            }
            System.out.println(count);
            int c=count-3;
            rs=st.executeQuery("select * from task");
            int i=0,jj=0;
            
                while(rs.next()){
                    i++;
                    System.out.println(i+" c : "+c);
                    if(i>c){
                        taskId= rs.getString(1);
                        e[jj]=rs.getDouble(3);
                        w[jj]=rs.getDouble(4);
                        b=rs.getDouble(6);
                        System.out.println(taskId+" "+e[jj]+" "+w[jj]+" "+b+" jval : "+jj+" ival : "+i);
                    jj++;
                    }
                }
//            int i=0;
            
//            rs=st.executeQuery("select * from task");
//            while(rs.next()){
//                taskId= rs.getString(1);
//                e[i]=rs.getDouble(3);
//                w[i]=rs.getDouble(4);
//                b=rs.getDouble(6);
//                i++;
//                if(i==2)
//                    break;
//            }
//            System.out.println(taskId+" "+e+" "+w+" "+b);
            ArrayList<Double> ea=new ArrayList<Double>();
            ArrayList<Double> wa=new ArrayList<Double>();
            for(int j=0;j<e.length;j++){
                ea.add(e[j]);
                wa.add(w[j]);
            }
            jTextArea1.append("Execute Task "+taskId+" with constraints "+ea+" "+wa+" "+b);
            st.executeUpdate("insert into query values('"+taskId+"',"+e[0]+","+e[1]+","+e[2]+","+w[0]+","+w[1]+","+w[2]+","+b+")");
            JOptionPane.showMessageDialog(null,"Query sent successfully!");
            RSelandAll r=new RSelandAll();
            r.setVisible(true);
            
        } catch (Exception e) {
            System.out.println("Exception : " + e);
        }
    }//GEN-LAST:event_queryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResourceQuery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResourceQuery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResourceQuery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResourceQuery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ResourceQuery().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton query;
    // End of variables declaration//GEN-END:variables
}
