/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package soc4;

import java.sql.*;


/**
 *
 * @author user
 */
public class P2DimensionVector extends javax.swing.JFrame {

    public static double[] cv=new double[3];
    public static double[] pv=new double[3];
    public static double cpd=Provider1.cpd;
    public static double pmb=Provider1.pmb;
    public static double smb=Provider1.smb;
    int port = 1400;
    
    Connection con;
    Statement st;
    /**
     * Creates new form P2DimensionVector
     */
    public P2DimensionVector() {
        
        initComponents();
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/socDB","root","");
            st=con.createStatement();
        }
        catch(Exception e){
            System.out.println("Exception : "+e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        V = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Provider1aVector");
        setMinimumSize(new java.awt.Dimension(920, 540));
        getContentPane().setLayout(null);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 110, 900, 10);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 160, 900, 10);

        V.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        V.setForeground(new java.awt.Color(0, 102, 255));
        V.setText("Dimension Vectors");
        V.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 204, 255), new java.awt.Color(102, 204, 255), null, null));
        V.setContentAreaFilled(false);
        V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VActionPerformed(evt);
            }
        });
        getContentPane().add(V);
        V.setBounds(30, 120, 180, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Capacity Vector", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18), new java.awt.Color(0, 102, 255))); // NOI18N
        jPanel1.setOpaque(false);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Traditional Arabic", 0, 22)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(340, 200, 160, 260);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resource Price Vector", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18), new java.awt.Color(0, 102, 255))); // NOI18N
        jPanel2.setOpaque(false);

        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Traditional Arabic", 0, 22)); // NOI18N
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(510, 200, 180, 260);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resources", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18), new java.awt.Color(0, 102, 255))); // NOI18N
        jPanel3.setOpaque(false);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Traditional Arabic", 0, 22)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 200, 320, 260);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tit.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VActionPerformed
        // TODO add your handling code here:
        try
        {
            //jTextArea1.append("-------------------\nResources\n-------------------\n\n");
            jTextArea1.append("Free Physical Memory\n\n");
            jTextArea1.append("Current CPU Usage\n\n");
            jTextArea1.append("Virtual Memory Size");
            cv[0]=pmb;
            cv[1]=cpd;
            cv[2]=smb;            
//            System.out.println("capacity Vector : "+cv);
            //==============Physical memory price 5% of physicalmem value================
            String pa=String.valueOf(pmb);
            int pdi=pa.indexOf(".");
            String p1=pa.substring(0, pdi);
            String p2=pa.substring(pdi+1);
            String p3="";
            if(pa.length()==3){
                p3=p1+p2+"0";
            }
            else
                p3=p1+p2;
            double pmbV=Double.parseDouble(p3);
            double pPrice=(pmbV*5)/100;
//            System.out.println(pmbV+" "+pPrice);
            pv[0]=pPrice;
            
            
            //==============CPU memory price 0.5% of cpu value================
            String ca=String.valueOf(cpd);
            int cdi=ca.indexOf(".");
            String c1=ca.substring(0, cdi);
            String c2=ca.substring(cdi+1);
            String c3="";
            if(ca.length()==3){
                c3=c1+c2+"0";
            }
            else
                c3=c1+c2;
            double cmbV=Double.parseDouble(c3);
            double cPrice=(cmbV * 0.5)/100;
//            System.out.println(cmbV+" "+cPrice);
            pv[1]=cPrice;
            
            //==============Swap memory price 5% of swap value================
            String sa=String.valueOf(smb);
            int sdi=sa.indexOf(".");
            String s1=sa.substring(0, sdi);
            String s2=sa.substring(sdi+1);
            String s3="";
            if(sa.length()==3){
                s3=s1+s2+"0";
            }
            else
                s3=s1+s2;
            double smbV=Double.parseDouble(s3);
            double sPrice=(smbV*5)/100;
//            System.out.println(smbV+" "+sPrice);
            pv[2]=sPrice;
            
            //==============Dimension Vector Display================
            for(int i=0;i<cv.length;i++){
                jTextArea2.append(cv[i]+"");
                jTextArea3.append(pv[i]+"");
                if(i == (cv.length-1)){}
                else{
                    jTextArea2.append("\n\n");
                    jTextArea3.append("\n\n");
                }                                
            }
            st.executeUpdate("insert into can values('0',"+cv[0]+","+cv[1]+","+cv[2]+","+pv[0]+","+pv[1]+","+pv[2]+","+port+")");
        }
        catch(Exception e){
            System.out.println("Exception "+e);
        }
    }//GEN-LAST:event_VActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(P2DimensionVector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(P2DimensionVector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(P2DimensionVector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(P2DimensionVector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new P2DimensionVector().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton V;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
}
